# Generated by Django 2.1.4 on 2018-12-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='url',
            new_name='address',
        ),
    ]
