# Generated by Django 2.1.4 on 2018-12-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20181221_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('website', 'identifier')},
        ),
    ]
